export interface Country {
  code: string;
  name: string;
  businessRegNoLabel: string;
  businessRegNoFormat: string;
  businessRegNoPattern: RegExp;
}

export const COUNTRIES: Country[] = [
  {
    code: 'KR',
    name: 'South Korea',
    businessRegNoLabel: 'Business Registration Number',
    businessRegNoFormat: '123-45-67890',
    businessRegNoPattern: /^\d{3}-\d{2}-\d{5}$/,
  },
  {
    code: 'JP',
    name: 'Japan',
    businessRegNoLabel: 'Corporate Number',
    businessRegNoFormat: '1234567890123',
    businessRegNoPattern: /^\d{13}$/,
  },
  {
    code: 'CN',
    name: 'China',
    businessRegNoLabel: 'Unified Social Credit Code',
    businessRegNoFormat: '91110000000000000A',
    businessRegNoPattern: /^[0-9A-Z]{18}$/,
  },
  {
    code: 'SG',
    name: 'Singapore',
    businessRegNoLabel: 'UEN',
    businessRegNoFormat: '201234567A',
    businessRegNoPattern: /^[0-9]{8,10}[A-Z]$/,
  },
  {
    code: 'HK',
    name: 'Hong Kong',
    businessRegNoLabel: 'Business Registration Number',
    businessRegNoFormat: '12345678-000-01-23-4',
    businessRegNoPattern: /^\d{8}-\d{3}-\d{2}-\d{2}-\d$/,
  },
  {
    code: 'TW',
    name: 'Taiwan',
    businessRegNoLabel: 'Business Administration Number',
    businessRegNoFormat: '12345678',
    businessRegNoPattern: /^\d{8}$/,
  },
  {
    code: 'IN',
    name: 'India',
    businessRegNoLabel: 'CIN',
    businessRegNoFormat: 'U12345KA2020PTC123456',
    businessRegNoPattern: /^[A-Z]\d{5}[A-Z]{2}\d{4}[A-Z]{3}\d{6}$/,
  },
  {
    code: 'TH',
    name: 'Thailand',
    businessRegNoLabel: 'Tax ID',
    businessRegNoFormat: '1234567890123',
    businessRegNoPattern: /^\d{13}$/,
  },
  {
    code: 'VN',
    name: 'Vietnam',
    businessRegNoLabel: 'Tax Code',
    businessRegNoFormat: '0123456789',
    businessRegNoPattern: /^\d{10}$/,
  },
  {
    code: 'MY',
    name: 'Malaysia',
    businessRegNoLabel: 'Company Registration Number',
    businessRegNoFormat: '123456-A',
    businessRegNoPattern: /^\d{6}-[A-Z]$/,
  },
  {
    code: 'PH',
    name: 'Philippines',
    businessRegNoLabel: 'TIN',
    businessRegNoFormat: '123-456-789-000',
    businessRegNoPattern: /^\d{3}-\d{3}-\d{3}-\d{3}$/,
  },
  {
    code: 'ID',
    name: 'Indonesia',
    businessRegNoLabel: 'NPWP',
    businessRegNoFormat: '12.345.678.9-012.345',
    businessRegNoPattern: /^\d{2}\.\d{3}\.\d{3}\.\d-\d{3}\.\d{3}$/,
  },
  {
    code: 'US',
    name: 'United States',
    businessRegNoLabel: 'EIN',
    businessRegNoFormat: '12-3456789',
    businessRegNoPattern: /^\d{2}-\d{7}$/,
  },
  {
    code: 'CA',
    name: 'Canada',
    businessRegNoLabel: 'Business Number',
    businessRegNoFormat: '123456789RC0001',
    businessRegNoPattern: /^\d{9}RC\d{4}$/,
  },
  {
    code: 'MX',
    name: 'Mexico',
    businessRegNoLabel: 'RFC',
    businessRegNoFormat: 'ABC123456ABC',
    businessRegNoPattern: /^[A-Z]{3}\d{6}[A-Z0-9]{3}$/,
  },
  {
    code: 'GB',
    name: 'United Kingdom',
    businessRegNoLabel: 'Company Registration Number',
    businessRegNoFormat: '12345678',
    businessRegNoPattern: /^[A-Z0-9]{8}$/,
  },
  {
    code: 'DE',
    name: 'Germany',
    businessRegNoLabel: 'Handelsregisternummer',
    businessRegNoFormat: 'HRB 12345',
    businessRegNoPattern: /^[A-Z]{3}\s?\d{1,6}$/,
  },
  {
    code: 'FR',
    name: 'France',
    businessRegNoLabel: 'SIREN',
    businessRegNoFormat: '123456789',
    businessRegNoPattern: /^\d{9}$/,
  },
  {
    code: 'IT',
    name: 'Italy',
    businessRegNoLabel: 'Codice Fiscale',
    businessRegNoFormat: '12345678901',
    businessRegNoPattern: /^\d{11}$/,
  },
  {
    code: 'ES',
    name: 'Spain',
    businessRegNoLabel: 'CIF',
    businessRegNoFormat: 'A12345678',
    businessRegNoPattern: /^[A-Z]\d{8}$/,
  },
  {
    code: 'NL',
    name: 'Netherlands',
    businessRegNoLabel: 'KVK Number',
    businessRegNoFormat: '12345678',
    businessRegNoPattern: /^\d{8}$/,
  },
  {
    code: 'SE',
    name: 'Sweden',
    businessRegNoLabel: 'Organisationsnummer',
    businessRegNoFormat: '123456-7890',
    businessRegNoPattern: /^\d{6}-\d{4}$/,
  },
  {
    code: 'CH',
    name: 'Switzerland',
    businessRegNoLabel: 'UID',
    businessRegNoFormat: 'CHE-123.456.789',
    businessRegNoPattern: /^CHE-\d{3}\.\d{3}\.\d{3}$/,
  },
  {
    code: 'NO',
    name: 'Norway',
    businessRegNoLabel: 'Organisasjonsnummer',
    businessRegNoFormat: '123456789',
    businessRegNoPattern: /^\d{9}$/,
  },
  {
    code: 'DK',
    name: 'Denmark',
    businessRegNoLabel: 'CVR',
    businessRegNoFormat: '12345678',
    businessRegNoPattern: /^\d{8}$/,
  },
  {
    code: 'FI',
    name: 'Finland',
    businessRegNoLabel: 'Y-tunnus',
    businessRegNoFormat: '1234567-8',
    businessRegNoPattern: /^\d{7}-\d$/,
  },
  {
    code: 'PL',
    name: 'Poland',
    businessRegNoLabel: 'NIP',
    businessRegNoFormat: '123-456-78-90',
    businessRegNoPattern: /^\d{3}-\d{3}-\d{2}-\d{2}$/,
  },
  {
    code: 'BE',
    name: 'Belgium',
    businessRegNoLabel: 'Enterprise Number',
    businessRegNoFormat: '0123.456.789',
    businessRegNoPattern: /^\d{4}\.\d{3}\.\d{3}$/,
  },
  {
    code: 'AT',
    name: 'Austria',
    businessRegNoLabel: 'Firmenbuchnummer',
    businessRegNoFormat: '123456a',
    businessRegNoPattern: /^\d{6}[a-z]$/,
  },
  {
    code: 'IE',
    name: 'Ireland',
    businessRegNoLabel: 'Company Registration Number',
    businessRegNoFormat: '123456',
    businessRegNoPattern: /^\d{6}$/,
  },
  {
    code: 'AU',
    name: 'Australia',
    businessRegNoLabel: 'ABN',
    businessRegNoFormat: '12 345 678 901',
    businessRegNoPattern: /^\d{2}\s\d{3}\s\d{3}\s\d{3}$/,
  },
  {
    code: 'NZ',
    name: 'New Zealand',
    businessRegNoLabel: 'NZBN',
    businessRegNoFormat: '1234567890123',
    businessRegNoPattern: /^\d{13}$/,
  },
  {
    code: 'AE',
    name: 'United Arab Emirates',
    businessRegNoLabel: 'Trade License Number',
    businessRegNoFormat: '123456',
    businessRegNoPattern: /^\d{6,10}$/,
  },
  {
    code: 'SA',
    name: 'Saudi Arabia',
    businessRegNoLabel: 'Commercial Registration',
    businessRegNoFormat: '1234567890',
    businessRegNoPattern: /^\d{10}$/,
  },
  {
    code: 'IL',
    name: 'Israel',
    businessRegNoLabel: 'Company Number',
    businessRegNoFormat: '123456789',
    businessRegNoPattern: /^\d{9}$/,
  },
  {
    code: 'BR',
    name: 'Brazil',
    businessRegNoLabel: 'CNPJ',
    businessRegNoFormat: '12.345.678/0001-90',
    businessRegNoPattern: /^\d{2}\.\d{3}\.\d{3}\/\d{4}-\d{2}$/,
  },
  {
    code: 'AR',
    name: 'Argentina',
    businessRegNoLabel: 'CUIT',
    businessRegNoFormat: '12-34567890-1',
    businessRegNoPattern: /^\d{2}-\d{8}-\d$/,
  },
  {
    code: 'CL',
    name: 'Chile',
    businessRegNoLabel: 'RUT',
    businessRegNoFormat: '12.345.678-9',
    businessRegNoPattern: /^\d{1,2}\.\d{3}\.\d{3}-[\dkK]$/,
  },
  {
    code: 'ZA',
    name: 'South Africa',
    businessRegNoLabel: 'Company Registration Number',
    businessRegNoFormat: '2023/123456/07',
    businessRegNoPattern: /^\d{4}\/\d{6}\/\d{2}$/,
  },
  {
    code: 'EG',
    name: 'Egypt',
    businessRegNoLabel: 'Tax Card Number',
    businessRegNoFormat: '123-456-789',
    businessRegNoPattern: /^\d{3}-\d{3}-\d{3}$/,
  },
  {
    code: 'RU',
    name: 'Russia',
    businessRegNoLabel: 'OGRN',
    businessRegNoFormat: '1234567890123',
    businessRegNoPattern: /^\d{13}$/,
  },
  {
    code: 'TR',
    name: 'Turkey',
    businessRegNoLabel: 'Tax Number',
    businessRegNoFormat: '1234567890',
    businessRegNoPattern: /^\d{10}$/,
  },
];
